-- MySQL Script generated by MySQL Workbench
-- Tue Dec  2 22:52:35 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema afores
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema afores
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `afores` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `afores` ;

-- -----------------------------------------------------
-- Table `afores`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `afores`.`clientes` (
  `id_cliente` INT NOT NULL AUTO_INCREMENT,
  `curp` VARCHAR(18) NOT NULL,
  `nombre` VARCHAR(100) NOT NULL,
  `apellido_paterno` VARCHAR(100) NOT NULL,
  `apellido_materno` VARCHAR(100) NOT NULL,
  `correo` VARCHAR(100) NOT NULL,
  `telefono` VARCHAR(10) NULL DEFAULT NULL,
  `estado` TINYINT(1) NOT NULL DEFAULT '1',
  PRIMARY KEY (`id_cliente`),
  UNIQUE INDEX `CURP_UNIQUE` (`curp` ASC) VISIBLE,
  UNIQUE INDEX `id_cliente_UNIQUE` (`id_cliente` ASC) VISIBLE,
  UNIQUE INDEX `correo_UNIQUE` (`correo` ASC) VISIBLE,
  UNIQUE INDEX `telefono_UNIQUE` (`telefono` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 50
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `afores`.`estatus_solicitud`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `afores`.`estatus_solicitud` (
  `id_estatus` INT NOT NULL AUTO_INCREMENT,
  `nombre_estatus` ENUM('EN_PROCESO', 'VALIDADA', 'RECHAZADA') NOT NULL,
  `estado` TINYINT(1) NOT NULL DEFAULT '1',
  PRIMARY KEY (`id_estatus`),
  UNIQUE INDEX `unique_nombre_estatus` (`nombre_estatus` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `afores`.`solicitudes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `afores`.`solicitudes` (
  `id_solicitud` INT NOT NULL AUTO_INCREMENT,
  `id_cliente` INT NOT NULL,
  `fecha` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `id_estatus` INT NOT NULL,
  `estado` TINYINT(1) NOT NULL DEFAULT '1',
  PRIMARY KEY (`id_solicitud`),
  INDEX `id_cliente_idx` (`id_cliente` ASC) VISIBLE,
  INDEX `id_estatus_idx` (`id_estatus` ASC) VISIBLE,
  CONSTRAINT `id_cliente`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `afores`.`clientes` (`id_cliente`),
  CONSTRAINT `id_estatus`
    FOREIGN KEY (`id_estatus`)
    REFERENCES `afores`.`estatus_solicitud` (`id_estatus`))
ENGINE = InnoDB
AUTO_INCREMENT = 80
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `afores`.`correccion_de_datos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `afores`.`correccion_de_datos` (
  `id_correccion` INT NOT NULL AUTO_INCREMENT,
  `id_solicitud` INT NOT NULL,
  `campo_modificado` VARCHAR(100) NOT NULL,
  `valor_anterior` VARCHAR(100) NULL DEFAULT NULL,
  `valor_nuevo` VARCHAR(100) NULL DEFAULT NULL,
  `fecha_corrección` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `estado` TINYINT(1) NOT NULL DEFAULT '1',
  `fecha_correccion` DATETIME(6) NULL DEFAULT NULL,
  PRIMARY KEY (`id_correccion`),
  INDEX `id_solicitud_idx` (`id_solicitud` ASC) VISIBLE,
  CONSTRAINT `id_solicitud`
    FOREIGN KEY (`id_solicitud`)
    REFERENCES `afores`.`solicitudes` (`id_solicitud`))
ENGINE = InnoDB
AUTO_INCREMENT = 23
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `afores`.`video_de_consentimiento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `afores`.`video_de_consentimiento` (
  `id_video` INT NOT NULL AUTO_INCREMENT,
  `id_solicitud` INT NOT NULL,
  `fecha` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `url_video` VARCHAR(250) NULL DEFAULT NULL,
  `estado` TINYINT(1) NOT NULL DEFAULT '1',
  PRIMARY KEY (`id_video`),
  INDEX `id_solicitud_idx` (`id_solicitud` ASC) VISIBLE,
  CONSTRAINT `id_video_solicitud`
    FOREIGN KEY (`id_solicitud`)
    REFERENCES `afores`.`solicitudes` (`id_solicitud`))
ENGINE = InnoDB
AUTO_INCREMENT = 57
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
